{% set name = "LHCbDIRAC" %}
{% set version = "10r0p1" %}
{% set major = version.split('r')[0] %}
{% set minor = version.split('r')[1].split('p')[0] %}
{% set patch = version.split('p')[1] %}

package:
  name: {{ name|lower }}
  version: {{ major }}.{{ minor }}.{{ patch }}

source:
  url: https://gitlab.cern.ch/lhcb-dirac/{{ name }}/-/archive/v{{ major }}r{{ minor }}p{{ patch }}/LHCbDIRAC-v{{ major }}r{{ minor }}p{{ patch }}.tar.gz
  sha256: 7eadf83c1c707b3826e763c0946004ea5bad9808b0519618382f3b267dcc7023

build:
  noarch: python
  number: 1
  script:
    - cp ${RECIPE_DIR}/setup.py .
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - mkdir -p ${CONDA_PREFIX}/scripts
    - find LHCbDIRAC -wholename '*/scripts/*.py' -exec bash -xc 'FN={} && NEW_FN=${CONDA_PREFIX}/scripts/$(basename ${FN} .py) && echo cp ${FN} ${NEW_FN} && chmod +x ${NEW_FN}' \;
    - find LHCbDIRAC -wholename '*/scripts/*.py' -exec bash -xc 'FN={} && NEW_FN=${CONDA_PREFIX}/bin/$(basename ${FN} .py) && echo cp ${FN} ${NEW_FN} && chmod +x ${NEW_FN}' \;

requirements:
  host:
    - python =2.7
    - pip
  run:
    - python =2.7
    - dirac-grid =7.0
    - lhcbdirac-config
    - voms
    - python-gfal2
    - lbplatformutils >=4.2.3
    - lbenv >=1.1.1

test:
  imports:
    - LHCbDIRAC

about:
  home: https://lhcb-dirac.readthedocs.io/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'LHCbDIRAC is the Extension to DIRAC for the LHCb Experiment'
  description: |
    DIRAC forms a layer between a particular community and various compute
    resources to allow optimized, transparent and reliable usage. LHCbDIRAC
    specializes DIRAC for LHCb.
  doc_url: https://lhcb-dirac.readthedocs.io/
  dev_url: https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC

extra:
  recipe-maintainers:
    - chrisburr
